networks:
  app:
    driver: bridge

services:
  api:
    build: .
    ports:
      - "3001:3001"
    expose:
      - "3001"
    networks:
      - app
    restart: always
  db:
    build: ./server
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./server/db.json:/data/db.json
    networks:
      - app
