version: "3"

networks:
  app:
    driver: bridge

services:
  api:
    build: .
    ports:
      - "3001:3001"
    expose:
      - "3001"
    volumes:
      - ./src:/app/src
    networks:
      - app
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/